// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace WebEshopTests
{

    [TestFixture]
    public class CouponRemovalTests
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        private string baseURL;

        [SetUp]

        public void SetUp()
        {
            driver = new FirefoxDriver();
            baseURL = "http://open-eshop.stqa.ru/oc-panel/auth/login";
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void CouponRemovalTest()
        {
            GoToHomePage();


        }

        private void GoToHomePage()
        {
            driver.Navigate().GoToUrl(baseURL);
            Login();
            //coupon page
            driver.FindElement(By.XPath("//a/span[2]")).Click();
            driver.FindElement(By.XPath("//tr[4]/td/li/a/span")).Click();
            // selectcoupon
            driver.FindElement(By.XPath("//td[7]/a[2]/i")).Click();
            driver.FindElement(By.XPath("//button[2]")).Click();
            driver.FindElement(By.XPath("//a[contains(@href, \'#\')]")).Click();
            driver.FindElement(By.XPath("//li[6]/a")).Click();
        }

        private void Login()
        {
            driver.FindElement(By.XPath("(//input[@name=\'email\'])[4]")).Click();
            driver.FindElement(By.XPath("(//input[@name=\'email\'])[4]")).SendKeys("demo@open-eshop.com");
            driver.FindElement(By.XPath("(//input[@name=\'password\'])[2]")).Click();
            driver.FindElement(By.XPath("(//input[@name=\'password\'])[2]")).SendKeys("demo");
            driver.FindElement(By.XPath("(//button[@type=\'submit\'])[5]")).Click();
        }
    }

}


